version: 0.2

env:
  shell: bash

phases:
  pre_build:
    commands:
      - set -euo pipefail
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
      - TAG="$(echo "$CODEBUILD_RESOLVED_SOURCE_VERSION" | cut -c1-7)"
      - echo "Using image tag: $TAG"
      - test -n "$TAG"

  build:
    commands:
      - echo "Build API image..."
      - docker build -f src/Dockerfile.api -t "$API_REPO:$TAG" .
      - echo "Build UI (Streamlit) image..."
      - docker build -f src/Dockerfile.app_streamlit -t "$UI_REPO:$TAG" .
      - echo "Tag images for ECR..."
      - docker tag "$API_REPO:$TAG" "$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$API_REPO:$TAG"
      - docker tag "$UI_REPO:$TAG" "$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$UI_REPO:$TAG"

  post_build:
    commands:
      - echo "Push images to ECR..."
      - docker push "$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$API_REPO:$TAG"
      - docker pus


