version: 0.2

env:
  shell: bash
  variables:
    AWS_REGION: "eu-west-2"
    ACCOUNT_ID: "430006376054"
    API_REPO: "suganthy-api"
    UI_REPO: "suganthy-streamlit"
    API_CONTAINER_NAME: "suganthy-api"
    UI_CONTAINER_NAME: "suganthy-streamlit"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - 'set -euo pipefail'
      - 'echo "Installing Python dependencies..."'
      - 'python -m pip install --upgrade pip'
      - 'pip install -r requirements.txt'

  pre_build:
    commands:
      - 'echo "Checking MLflow config..."'
      - 'test -n "${MLFLOW_TRACKING_URI:-}" || (echo "ERROR: MLFLOW_TRACKING_URI not set" && exit 1)'
      - 'echo "Running training and registering model to MLflow..."'
      - 'python main.py'
      - 'echo "Logging in to Amazon ECR..."'
      - 'aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"'
      - 'TAG="$(echo "$CODEBUILD_RESOLVED_SOURCE_VERSION" | cut -c1-7)"'
      - 'echo "Using image tag: $TAG"'

  build:
    commands:
      - 'echo "Building API image..."'
      - 'docker build -f src/Dockerfile.api -t "$API_REPO:$TAG" .'
      - 'echo "Building Streamlit UI image..."'
      - 'docker build -f src/Dockerfile.app_streamlit -t "$UI_REPO:$TAG" .'
      - 'echo "Tagging images..."'
      - 'docker tag "$API_REPO:$TAG" "$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$API_REPO:$TAG"'
      - 'docker tag "$UI_REPO:$TAG" "$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$UI_REPO:$TAG"'

  post_build:
    commands:
      - 'echo "Pushing images to ECR..."'
      - 'docker push "$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$API_REPO:$TAG"'
      - 'docker push "$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$UI_REPO:$TAG"'
      - 'echo "Creating imagedefinitions files..."'
      - 'printf ''[{"name":"%s","imageUri":"%s"}]'' "$API_CONTAINER_NAME" "$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$API_REPO:$TAG" > imagedefinitions-api.json'
      - 'printf ''[{"name":"%s","imageUri":"%s"}]'' "$UI_CONTAINER_NAME" "$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$UI_REPO:$TAG" > imagedefinitions-ui.json'
      - 'cp imagedefinitions-api.json imagedefinitions.json'
      - 'echo "Artifacts:"'
      - 'ls -la'
      - 'cat imagedefinitions-api.json'
      - 'cat imagedefinitions-ui.json'
      - 'cat imagedefinitions.json'

artifacts:
  files:
    - imagedefinitions.json
    - imagedefinitions-api.json
    - imagedefinitions-ui.json