version: 0.2

env:
  variables:
    AWS_REGION: eu-west-2
    API_REPO: mlops-api
    UI_REPO: mlops-ui
    API_CONTAINER_NAME: mary-mlops-api
    UI_CONTAINER_NAME: mary-mlops-ui

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - aws ecr get-login-password --region $AWS_REGION |
        docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH}
      - echo "Image tag: $IMAGE_TAG"

  build:
    commands:
      - echo "Build API image"
      - docker build -t $API_REPO:$IMAGE_TAG -f Dockerfile .

      - echo "Build UI (Streamlit) image"
      - docker build -t $UI_REPO:$IMAGE_TAG -f src/Dockerfile.app_streamlit .

      - echo "Tag images"
      - docker tag $API_REPO:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$API_REPO:$IMAGE_TAG
      - docker tag $UI_REPO:$IMAGE_TAG  $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$UI_REPO:$IMAGE_TAG

  post_build:
    commands:
      - echo "Push images to ECR"
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$API_REPO:$IMAGE_TAG
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$UI_REPO:$IMAGE_TAG

      - echo "Create combined imagedefinitions.json"
      - |
        printf '[{"name":"%s","imageUri":"%s"},{"name":"%s","imageUri":"%s"}]' \
        "$API_CONTAINER_NAME" "$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$API_REPO:$IMAGE_TAG" \
        "$UI_CONTAINER_NAME"  "$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$UI_REPO:$IMAGE_TAG" \
        > imagedefinitions.json

      - echo "imagedefinitions.json:"
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
