FROM python:3.11-slim
WORKDIR /app

RUN pip install --no-cache-dir mlflow

# Your project not required for mlflow server, but keeping it simple:
COPY . .

EXPOSE 5000

CMD ["mlflow", "server", \
     "--host", "0.0.0.0", \
     "--port", "5000", \
     "--backend-store-uri", "sqlite:////app/mlflow.db", \
     "--default-artifact-root", "/app/artifacts"]
