FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ /app/
COPY data/ /app/data/

EXPOSE 8501
CMD ["streamlit", "run", "app_streamlit_combined.py", "--server.port=8501", "--server.address=0.0.0.0"]