FROM python:3.12-slim

WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir fastapi uvicorn joblib pandas scikit-learn pydantic

# Copy ONLY api file from src
COPY src/api.py .

# Copy trained model into container
COPY models/student_performance_sgd.joblib models/student_performance_sgd.joblib

# Expose FastAPI port
EXPOSE 8000

# Run FastAPI
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]