FROM python:3.12-slim

WORKDIR /app

# Install dependencies (add uvicorn)
RUN pip install --no-cache-dir streamlit requests pandas uvicorn

COPY src/app_streamlit.py .

EXPOSE 8501

CMD ["streamlit", "run", "app_streamlit.py", "--server.port=8501", "--server.address=0.0.0.0"]
